# Coding Battle - 2019

## Imports

In [1]:
import math
import numpy as np

In [2]:
from collections import Counter 


## TEST

In [3]:
arr = [1, 2, 3, 1, 1]

In [4]:
counter = Counter(arr)

In [7]:
counter.most_common(3)

[(1, 3), (2, 1), (3, 1)]

## Exercices

### Exo 1

### Exo 2

In [8]:
a = [0, 1, 2, 3]

In [10]:
a[2:]

[2, 3]

In [36]:
import math

local = '10:80'
M = 2
H = 90

hh = int(local[:2])
mm = int(local[3:])

terr_min = (hh * H + mm) / M
print(terr_min)


hour = (terr_min//60)%24
minutes = terr_min-(terr_min//60 * 60)
result = "{:.0f}:{:.0f}".format(hour, minutes)

print(result)

490.0
8:10


In [22]:
int('01:01'[:2])

1

In [20]:
3000//60

50

In [39]:

local = str(input())
M = int(input())
H = int(input())

hh = int(local[:2])
mm = int(local[3:])

terr_min = (hh * H + mm) / M
print(terr_min)

hour = (terr_min//60) % 24
minutes = terr_min%60
result = "{:.0f}:{:.0f}".format(hour, minutes)

print (result)

 20:00
 2
 300


3000.0
2:0


### Exo 3

In [42]:
noms = ['']*5
noms

['', '', '', '', '']

In [2]:
noms = ['']*2

x = dict()
y = dict()

for i in range(2):
    noms[i] = input()
    x[i] = [0]*3
    y[i] = [0]*3
    for j in range(3):
        x[i][j], y[i][j] = map(float, input().split(" "))

 magneto
 0 100
 100 200
 200 300
 furio
 -1 2
 2 3
 3 4


In [3]:
x

{0: [0.0, 100.0, 200.0], 1: [-1.0, 2.0, 3.0]}

In [16]:
import math

xb, yb = map(float, input().split(" "))
N, T = map(int, input().split(" "))

noms = ['']*N
x = dict()
y = dict()

for i in range(N):
    noms[i] = input()
    x[i] = [0]*T
    y[i] = [0]*T
    for j in range(T):
        x[i][j], y[i][j] = map(float, input().split(" "))


x_0 = dict(x)
y_0 = dict(y)

# for i in range(N):
#     for j in range(T):
#         x_0[i][j] = x_0[i][j] - xb
#         y_0[i][j] = y_0[i][j] - yb

resultat = ''
liste_noms = []
for i in range(N):
    possible = True
    possible_nom = True
    while possible:
        for t in range(T-1):
            dist = math.sqrt((x[i][t+1] - xb)**2 + (y_0[i][t+1] - yb)**2) + math.sqrt((x[i][t] - xb)**2 + (y_0[i][t] - yb)**2)
            print(noms[i], t, ': ', dist)
            if dist <= 100:
                possible = False
                possible_nom = False
        possible = False

    if possible_nom:
        liste_noms.append(noms[i])

print (' '.join(liste_noms))



 150 100
 2 8
 mag
 300 300
 325 250
 275 225
 225 250
 200 175
 125 150
 75 175
 50 225
 fat
 25 25
 50 75
 100 100
 175 75
 250 50
 275 100
 325 100
 350 175


mag 0 :  480.48861143232216
mag 1 :  407.2653067289591
mag 2 :  344.48179360912115
mag 3 :  257.84388019908397
mag 4 :  146.04048132409446
mag 5 :  161.9677166154769
mag 6 :  266.14412311380335
fat 0 :  248.85143801157403
fat 1 :  153.07764064044153
fat 2 :  85.35533905932738
fat 3 :  147.15873793431686
fat 4 :  236.80339887498948
fat 5 :  300.0
fat 6 :  388.6000936329383
mag


##### x_0

In [11]:
y_0

{0: [200.0, 150.0, 125.0, 150.0, 75.0, 50.0, 75.0, 125.0],
 1: [-75.0, -25.0, 0.0, -25.0, -50.0, 0.0, 0.0, 75.0]}

### Exo 4

In [1]:
import numpy as np

In [4]:
a = np.array([[1,2,3],[4,5,6]])

In [5]:
a[-1, -1]

6

In [6]:
a[-1][-1]

6

In [3]:
a.reshape(-1, )

array([1, 2, 3, 4, 5, 6])

In [3]:
import sys
print(sys.executable)
print(sys.version)
print(sys.version_info)

C:\ProgramData\Anaconda3\python.exe
3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)


In [7]:
import math
import numpy as np

# On récupère tous les inputs...
Q = int(input())
N = int(input())

jaune = []
bleu = []

for i in range(N):
    a = input()
    if int(a[0]) == 1:
        jaune.append(int(str(a)[2:]))
    else:
        bleu.append(int(str(a)[2:]))
# Les inputs ont tous été récupérés

# On construit la matrice des énergies de toutes les paires (jaune, bleu) possibles
matrix = np.zeros((len(jaune), len(bleu)))

for i in range(len(jaune)):
    for j in range(len(bleu)):
        matrix[i][j] = jaune[i] + bleu[j]

energy_values = matrix.reshape(-1, )

# On va appliquer l'algorithme de résolution du problème du sac à dos !!
n = len(energy_values)
tableau = np.zeros((n, Q))

tableau[0, :] = energy_values[0] * np.ones((1, Q))
for i in range(1, n):
    for j in range(Q):
        tableau[i, j] = max(energy_values[i] + tableau[i-1, j-1], tableau[i-1, j])

print(tableau[-1, -1])

 100
 6
 1 10
 1 50
 1 60
 2 30
 2 20
 2 60


690.0


In [8]:
matrix

array([[ 40.,  30.,  70.],
       [ 80.,  70., 110.],
       [ 90.,  80., 120.]])

In [9]:
np.sum(matrix)

690.0

In [12]:
matrix[[2,1,0]]

array([[ 90.,  80., 120.],
       [ 80.,  70., 110.],
       [ 40.,  30.,  70.]])

In [17]:
from itertools import permutations 
l = list(permutations(range(1, 4))) 


In [18]:
l

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]

In [21]:
import math
import numpy as np
from itertools import permutations


# On récupère tous les inputs...
Q = int(input())
N = int(input())

jaune = []
bleu = []

for i in range(N):
    a = input()
    if int(a[0]) == 1:
        jaune.append(int(str(a)[2:]))
    else:
        bleu.append(int(str(a)[2:]))
# Les inputs ont tous été récupérés

# On construit la matrice des énergies de toutes les paires (jaune, bleu) possibles
matrix = np.zeros((len(jaune), len(bleu)))

for i in range(len(jaune)):
    for j in range(len(bleu)):
        matrix[i][j] = jaune[i] + bleu[j]

#energy_values = matrix.reshape(-1, )

#### WORK IN PROGRESS ####
# On construit toutes les matrices binaires possibles de paires (jaune, bleu)
liste_jaune = list(permutations(range(len(jaune))))
liste_bleu = list(permutations(range(len(bleu))))

identity = np.eye(len(jaune), len(bleu))


result = 0

for k in range(len(jaune)):
    for l in range(len(bleu)):
        stochastic_matrix = identity[list(liste_jaune[k])][list(liste_bleu[l])]
        new_energy_values = np.multiply(matrix, stochastic_matrix)

        energy_values = new_energy_values.reshape(-1, )

        # On va appliquer l'algorithme de résolution du problème du sac à dos !!
        n = len(energy_values)
        tableau = np.zeros((n, Q))

        tableau[0, :] = energy_values[0] * np.ones((1, Q))
        for i in range(1, n):
            for j in range(Q):
                tableau[i, j] = max(energy_values[i] + tableau[i-1, j-1], tableau[i-1, j])

        result = max(result, tableau[-1, -1])

print(result)

 100
 4
 1 50
 1 60
 2 70
 2 60


240.0


### Exo 5

### Exo 6